name: CI
on:
  push:
    branches: [ develop ]
    #  tags:
            #      - 'v*'
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.ECR_NODE }}
          tags: type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
#      - 
#        name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: arn:aws:iam::234104157315:role/node_runner
#          aws-region: eu-central-1
#          role-session-name: GitHubActions
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.ECR_NODE }}
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          driver: docker
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
     #         latest
     #       ${{ github.sha }}
            ${{ steps.meta.outputs.tags }}
      - uses: actions/checkout@v2
        with:
          repository: 'obryndzii/btt-helm-charts'
          ref: 'refs/heads/master'
          path: 'charts'
          token: ${{ secrets.PAT }}
#      - uses: actions/checkout@v2
#        with:
#          repository: 'obryndzii/btt-docker-images'
#          ref: 'refs/heads/master'
#          path: 'images'
#          token: ${{ secrets.PAT }}
      - name: Deploy
        run: |
          echo ${{ steps.meta.outputs.tags }}
          helm upgrade --install node-app charts/node-app -n prod --set image.tag=${{ steps.meta.outputs.tags }}
