name: CI
on:
  push:
    branches: [ develop ]
    #  tags:
            #      - 'v*'
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#      -
#        name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: ${{ secrets.ECR_NODE }}
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.ECR_NODE }}
          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [registry."234104157315.dkr.ecr.eu-west-1.amazonaws.com/node"]
      - uses: actions/checkout@v2
        with:
          repository: 'obryndzii/btt-helm-charts'
          ref: 'refs/heads/master'
          path: 'charts'
          token: ${{ secrets.PAT }}
      - uses: actions/checkout@v2
        with:
          repository: 'obryndzii/btt-docker-images'
          ref: 'refs/heads/master'
          path: 'images'
          token: ${{ secrets.PAT }}
      - name: Check
        run: |
          pwd
          helm version 
#      - name: Install kubectl
#        run: |
#          curl -LO https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl
#          chmod +x ./kubectl
#          ./kubectl version --client
#          ./kubectl get svc
#          ./kubectl get pods
#          ./kubectl get ingress
#      - name: Install helm
#        run: |
#          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
#          chmod 700 get_helm.sh
#          ./get_helm.sh
#          helm list -A
#
