name: master-CI
on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      -
#        name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: ${{ secrets.ECR_NODE }}
      - 
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: eu-central-1
          role-session-name: GitHubActions
#      -
#        name: Login to ECR
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ secrets.ECR_NODE }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: |
#            ${{ secrets.ECR_NODE }}:latest
#            ${{ secrets.ECR_NODE }}:1.0.0
      - uses: actions/checkout@v2
        with:
          repository: 'obryndzii/btt-helm-charts'
          ref: 'refs/heads/master'
          path: 'charts'
          token: ${{ secrets.PAT }}
      - name: helm deploy
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          helm upgrade node-app --install --wait charts/node-app
#      - uses: actions/checkout@v2
#        with:
#          repository: 'obryndzii/btt-helm-charts'
#          ref: 'refs/heads/master'
#          path: 'charts'
#          token: ${{ secrets.PAT }}
#      - uses: actions/checkout@v2
#        with:
#          repository: 'obryndzii/btt-docker-images'
#          ref: 'refs/heads/master'
#          path: 'images'
#          token: ${{ secrets.PAT }}
