name: CI
on:
  push:
    branches: [ develop ]
    #  tags:
            #      - 'v*'
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#      -
#        name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: ${{ secrets.ECR_NODE }}
#      - 
#        name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: arn:aws:iam::234104157315:role/node_runner
#          aws-region: eu-central-1
#          role-session-name: GitHubActions
#      - name: Login to ECR
#        uses: docker/login-action@v1 
#        with:
#          registry: ${{ secrets.ECR_NODE }}
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ECR_NODE }}:latest
            ${{ secrets.ECR_NODE }}:1.0.0
      - uses: actions/checkout@v2
        with:
          repository: 'obryndzii/btt-helm-charts'
          ref: 'refs/heads/master'
          path: 'charts'
          token: ${{ secrets.PAT }}
      - uses: actions/checkout@v2
        with:
          repository: 'obryndzii/btt-docker-images'
          ref: 'refs/heads/master'
          path: 'images'
          token: ${{ secrets.PAT }}
      - name: Check
        run: |
          helm upgrade --install node-app charts/node-app -n prod
#      - name: Install kubectl
#        run: |
#          curl -LO https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl
#          chmod +x ./kubectl
#          ./kubectl version --client
#          ./kubectl get svc
#          ./kubectl get pods
#          ./kubectl get ingress
#      - name: Install helm
#        run: |
#          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
#          chmod 700 get_helm.sh
#          ./get_helm.sh
#          helm list -A
#
